volumes:
  grafana:
  prometheus:
  p2pool-data:

x-common-config: &common-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "20"

services: 
  prometheus:
    image: prom/prometheus:${PROM_TAG:-v2.36.0}
    command:
      - --config.file=/etc/prometheus/config.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROM_RETENTION:-360d}
    container_name: monerod_prometheus
    restart: unless-stopped
    profiles: [db all]
    # ports:
    #   - 127.0.0.1:9090:9090
    volumes:
      - prometheus:/prometheus
      - ${PROMETHEUS_FILES}/config.yaml:/etc/prometheus/config.yaml:ro
    <<: *common-config
  grafana:
    user: "1000"
    command:
      - -config=/etc/grafana/grafana.ini
    container_name: monerod_grafana
    restart: unless-stopped
    image: grafana/grafana:${GRAFANA_TAG:-10.1.4}
    ports:
      - ${GRAF_PORT:-3000}:3000
    volumes:
      - grafana:/var/lib/grafana
      - ${GRAFANA_FILES}/grafana.ini:/etc/grafana/grafana.ini:ro
      - ${GRAFANA_FILES}/provisioning:/etc/grafana/provisioning:ro
      - ${GRAFANA_FILES}/dashboards:/var/lib/grafana/dashboards:ro
    profiles: [db all]
    environment:
      HOSTNAME: grafana
      GF_SERVER_ROOT_URL: ${GRAFANA_URL}
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_LOG_LEVEL: "debug"
      GF_AUTH_ANONYMOUS_ENABLED: "${GF_AUTH_ANONYMOUS_ENABLED:-true}"
      GF_AUTH_BASIC_ENABLED: "${GF_AUTH_BASIC_ENABLED:-false}"
      GF_AUTH_DISABLE_LOGIN_FORM: "${GF_AUTH_DISABLE_LOGIN_FORM:-true}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    <<: *common-config
  exporter:
    container_name: monerod_exporter
    build:
      context: .
      dockerfile: dockerfiles/exporter
    restart: unless-stopped
    # ports:
    #   - 127.0.0.1:9000:9000
    profiles: [db all]
    command:
      - --monero-addr=http://monerod:${UNRESTRICTED_PORT:-18083}
    <<: *common-config
  nodemapper:
    container_name: monerod_nodemapper
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/nodemapper
    profiles: [db all]
    environment:
      NODE_HOST: monerod
      NODE_PORT: 18083
    # ports:
    #   - 127.0.0.1:${MAPPER_PORT:-5000}:5000
    <<: *common-config
  monerod:
    container_name: monerod
    build:
      context: .
      dockerfile: dockerfiles/monero
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-./data}:/data
      - ${CONFIG_FILE}:/monoconf.conf
    ports:
      - ${P2P_PORT:-18080}:18080                    # p2p
      - ${RESTRICTED_PORT:-18081}:18081             # restricted rpc
      - ${ZMQ_PORT:-18084}:18084                    # zmq
      - 127.0.0.1:${UNRESTRICTED_PORT:-18083}:18083 # unrestricted rpc
    profiles: [monerod all]
    command: |
      monerod
        --data-dir=/data --prune-blockchain
        --p2p-bind-ip=0.0.0.0 --p2p-bind-port=18080 
        --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=18081
        --zmq-pub=tcp://0.0.0.0:18084
        --rpc-bind-ip=0.0.0.0 --rpc-bind-port=18083 --rpc-ssl=disabled
        --non-interactive --confirm-external-bind
        --public-node --log-level=0
        --out-peers=128 --in-peers=128
        --limit-rate-up=21000 --limit-rate-down=21000
        --block-sync-size=10 --db-sync-mode=fastest:async:1000
        --no-igd --enable-dns-blocklist
        --add-priority-node=p2pmd.xmrvsbeast.com:18080
        --add-priority-node=nodes.hashvault.pro:18080
    <<: *common-config

  p2pool:
    image: sethsimmons/p2pool:latest
    restart: unless-stopped
    container_name: p2pool
    tty: true
    stdin_open: true
    profiles: [pool all]
    volumes:
      - p2pool-data:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    ports:
      - 3333:3333
      - 37889:37889
    command: >-
      --wallet "${P2POOL_WALLET}"
      --stratum "0.0.0.0:3333" --p2p "0.0.0.0:37889" --zmq-port "18084"
      --loglevel "0"
      --host "monerod" --rpc-port "18081" --mini
      --addpeers "65.21.227.114:37889,node.sethforprivacy.com:37889"
    <<: *common-config

  xmrig:
    image: metal3d/xmrig:latest
    restart: unless-stopped
    privileged: true
    container_name: xmrig
    profiles: [miner all]
    depends_on:
      - p2pool
    environment:
      POOL_URL: "p2pool:3333"
      POOL_USER: "${XMRIG_POOL_USER}"
      POOL_PASS: "${XMRIG_POOL_PASS}"
      PRIORITY: 0
      CUDA: "false"
      ACCESS_TOKEN: ${XMRIG_ACCESS_TOKEN}
    volumes:
      - /dev/hugepages:/dev/hugepages:rw
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    <<: *common-config
